import path from "node:path"
import {
	isFileSync,
	writeAtomicFileJSON
} from "@aniojs/node-fs"
import {
	createEntity,
	type EnkoreLockFile
} from "@enkore/spec"
import type {TargetIdentifier} from "@enkore/spec/primitives"
import {readEnkoreLockFile} from "./readEnkoreLockFile.mts"

export async function readEnkoreLockFileOrCreateIt(
	projectRoot: string, targetIdentifier: TargetIdentifier
) : Promise<EnkoreLockFile> {
	const lockfilePath = path.join(projectRoot, "enkore-lock.json")

	//
	// yes, this can/is racy but that shouldn't be an issue for us
	//
	if (isFileSync(lockfilePath)) {
		return await readEnkoreLockFile(projectRoot)
	}

	const lockfileData = createEntity("EnkoreLockFile", 0, 0, {
		targetIdentifier,
		autogeneratedFiles: {},
		targetDependencies: {},
		targetDependenciesStamp: ""
	})

	await writeAtomicFileJSON(lockfilePath, lockfileData, {
		pretty: true
	})

	return lockfileData
}
